### ISSUE TITLE
[feat] 감정일기 제공을 위한 gpt 연동 챗봇 서비스구현

### ISSUE THREAD

**Issue by bo-ram-bo-ram** [TeamS2-ICCAS2024/zen#3]
## 📌  Feature Issue

감정일기 제공을 위한 gpt연동을통한 챗봇 서비스를 구현합니다.

## 📝  To-do
<!— 해야 할 일들을 적어주세요. —>
- [x] 감정 선택하여 해당 이미지 다음페이지로 연동
- [x] ui 구현
- [x] gpt 연동 및 통신처리
- [x] api 키 변수처리

**Comment by wona825** [comment]
고생하셨습니다! 🙌🙂
