### ISSUE TITLE
[fix] 테트리스 게임 결과 중복 저장 오류 수정 

### ISSUE THREAD

**Issue by zvvony** [TeamS2-ICCAS2024/zen#62]
## 📌  Feature Issue

테트리스 게임 결과 저장 api 연결에서 발생하는 오류 해결
gpt api 연결 과정에서 발생하는 오류 해결

## 📝  To-do

- [x] 테트리스 게임 결과가 중복 저장되는 오류 해결 
- [x] httpClient SSL 인증서 오류 해결

**Comment by JunHyukYang** [comment]
👍👏
